#!/usr/bin/env python3
"""
prompt_memory.py — UserPromptSubmit hook
Reads your memory config and injects relevant context when your prompt matches a known topic.
Configure keywords in ~/.claude/memory-hooks/config.json (generated by /memory-setup).

No LLM calls. No API key needed. No external dependencies.
"""
import json
import sys
import subprocess
from pathlib import Path

HOME = Path.home()
CONFIG_PATH = HOME / ".claude" / "memory-hooks" / "config.json"

MIN_PROMPT_LEN = 12
MAX_CHARS_PER_FILE = 1200
MAX_TOTAL_CHARS = 3000


def load_config() -> dict:
    if not CONFIG_PATH.exists():
        return {}
    try:
        return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    except Exception:
        return {}


def get_project_slug(cwd: str) -> str:
    try:
        result = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            cwd=cwd, capture_output=True, text=True, timeout=3
        )
        if result.returncode == 0:
            remote = result.stdout.strip()
            name = remote.rstrip("/").split("/")[-1].replace(".git", "")
            if name:
                return name.lower()
    except Exception:
        pass
    return Path(cwd).name.lower().replace(" ", "-")


def get_memory_dir(cwd: str) -> Path:
    encoded = cwd.replace(":", "").replace("\\", "-").replace("/", "-").strip("-")
    return HOME / ".claude" / "projects" / encoded / "memory"


def find_relevant_files(prompt: str, config: dict, slug: str) -> list:
    """Find memory files relevant to this prompt."""
    prompt_lower = prompt.lower()
    found = []

    # Check user-defined keywords from config
    projects = config.get("projects", [])
    for project in projects:
        if project.get("slug") == slug:
            for keyword in project.get("keywords", []):
                if keyword.lower() in prompt_lower:
                    # Return this project's brief
                    found.append({"type": "brief", "slug": slug})
                    break

    return found


def read_brief(memory_dir: Path, slug: str) -> str:
    path = memory_dir / "session_briefs" / f"{slug}.md"
    if not path.exists():
        return ""
    content = path.read_text(encoding="utf-8", errors="replace")
    if content.startswith("---"):
        parts = content.split("---", 2)
        if len(parts) >= 3:
            content = parts[2].strip()
    return content[:MAX_CHARS_PER_FILE]


def main():
    try:
        data = json.loads(sys.stdin.buffer.read().decode("utf-8"))
    except Exception:
        sys.exit(0)

    prompt = data.get("prompt", "")
    cwd = data.get("cwd", "")

    if not prompt or len(prompt.strip()) < MIN_PROMPT_LEN:
        sys.exit(0)

    config = load_config()
    if not config:
        sys.exit(0)

    slug = get_project_slug(cwd)
    memory_dir = get_memory_dir(cwd)
    relevant = find_relevant_files(prompt, config, slug)

    if not relevant:
        sys.exit(0)

    sections = []
    total = 0
    for item in relevant:
        if total >= MAX_TOTAL_CHARS:
            break
        if item["type"] == "brief":
            content = read_brief(memory_dir, item["slug"])
            if content:
                sections.append(content)
                total += len(content)

    if not sections:
        sys.exit(0)

    combined = "\n\n---\n\n".join(sections)
    context = f"## Relevant memory\n\n{combined}"

    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "UserPromptSubmit",
            "additionalContext": context
        }
    }))


if __name__ == "__main__":
    main()
